### ISSUE TITLE
Ruby Has Characters - Errata - Wrong Hex Codes / Codepoints for A (its 41 and not 65)

### ISSUE THREAD

**Issue by geraldb** [janlelis/idiosyncratic-ruby.com#24]
Hello, First I love your great articles and your unmatched in-depth coverage.
While trying some examples from "https://idiosyncratic-ruby.com/66-ruby-has-character" I found some errors - you use:

    "\u{65}" # => "A"

as a codepoint example - but A is 65 in decimal and NOT in hex, thus you get 

    "\u{65}" # => "e"

You have to change 65 to 41 than all works as expected e.g.

       "\u{41}" # => "A"

And some more e.g.

    Codepoint | Decimal | 
    -- | -- | -- | -- | -- | --
    U+0065 | 101

needs to get corrected to:

    U+0041 | 65

Cheers. Prost.

**Comment by janlelis** [comment]
Hey Gerald, good catch! Thanks
