### ISSUE TITLE
What the pack: `V` and `N` definitions say _signed_ but they're really _unsigned_ 

### ISSUE THREAD

**Issue by h-lame** [janlelis/idiosyncratic-ruby.com#33]
In "What the pack" the definitions for [`N`](https://idiosyncratic-ruby.com/4-what-the-pack.html#n--a-signed-integer-per-4-bytes-big-endian-similar-to-l) and [`V`](https://idiosyncratic-ruby.com/4-what-the-pack.html#v--a-signed-integer-per-4-bytes-little-endian-similar-to-l) say they will generate _signed_ integers per 4 bytes, however the documentation for [`Array#pack`](https://ruby-doc.org/core-2.7.0/Array.html#method-i-pack) says that `N` and `V` will generate _unsigned_ 4-byte integers.  The "similar to" bits, `L>` for `N` and `L<` for `V`, are actually correct as `L` is an _unsigned_ integer per 4 bytes too.

I checked back so see if the definition for `N` or `V` had changed in older rubies, but it seems like they've always been to generate _unsigned_ values, so I'm guessing this is just a typo.

**Comment by janlelis** [comment]
Thanks for reporting and researching on this one!
